---
- name: "{{ epics_modules[item].name }} | Prepare extras installation dir"
  file:
    path: "/opt/opcua"
    state: directory
    mode: '0755'
  become: true

- name: "{{ epics_modules[item].name }} | Download the demo server"
  get_url:
    url: "https://github.com/epics-training/opcua-support/releases/download/v1.0/server_demo.tar.gz"
    dest: "/opt/opcua/server_demo.tar.gz"
  become: true

- name: "{{ epics_modules[item].name }} | Download the UaExpert client"
  get_url:
    url: "https://github.com/epics-training/opcua-support/releases/download/v1.0/ua_expert.AppImage"
    dest: "/opt/opcua/uaexpert.AppImage"
    mode: "555"
  become: true
